# https://github.com/mlocati/docker-php-extension-installer

FROM php:8.1-fpm-alpine

# ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/

RUN apk add --no-cache openssh git shadow

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod uga+x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions gd mysqli pdo_mysql xdebug @composer apcu opcache imagick exif zip intl sysvsem igbinary mcrypt pspell redis sockets ssh2 bcmath

